README.md

* Update README.md after driver server script restructuring
- ✅❌ https://github.com/DexaiRobotics/fullstack/pull/193 needs this PR
3. ❌ New code is written in pure C++17 to the best of my knowledge.
4. ❌ New code follows established C++17 best practices ([C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines)).
5. ❌ New code passed `clang-format` and `cpplint` at least, if not all of our static code analysers.
6. ❌ I have included Doxygen-style documentation in the new …

Update README.md after driver server script restructuring

---

include/examples_common.h
include/franka_plan_runner.h
src/franka_driver.cc
src/franka_plan_runner.cc

- Bump up high force and torque limit for collision detection on Franka
- 
1. ✅ Tested on simulated robot: Tested value gets set based on env var
2. ✅ Tested on physical robot: TLE on ranch
Please verify …

Safety off

---

franka.sh
src/franka_driver.cc
src/franka_plan_runner.cc

Division by zero is bad
1. ✅ Tested on simulated robot: paused robot, sent plan, unpaused
2. ✅ Tested on physical robot: paused robot, sent plan, unpaused
3. ✅New code is written in pure C++17 to the best of my knowledge.
Please verify that all sections are accurately filled out and that all 6 numbered entries above are …

Sw.unpause.new plan

---

include/communication_interface.h
include/types.h
include/util_conv.h
src/communication_interface.cc
src/franka_plan_runner.cc

- Cancel plans
- https://github.com/DexaiRobotics/deploy/pull/136
- https://github.com/DexaiRobotics/drake-franka-driver/pull/87
- https://github.com/DexaiRobotics/ancillary_arm/pull/78
- https://github.com/DexaiRobotics/dig/pull/623
1. ✅ Tested on simulated robot: pause, unpause, cancel
2. ✅ Tested on physical robot: pause, unpause, cancel
5. ✅ New code passed `clang-format` and `cpplint` at least, if not all of our static …

Initial version of canceling plan

---

src/driver/communication_interface.cc
src/driver/franka_plan_runner.cc
src/driver/franka_plan_runner.h

- ✅ New feature is accompanied by new test: [name and description of new test].
- ✅ This PR needs [link]
- ✅ [link] needs this PR
4. ✅ New code follows established …

better LCM error msg, add speed norm condition back, more turning

---

src/driver/communication_interface.cc
src/driver/communication_interface.h
src/driver/franka_plan_runner.cc
src/driver/franka_plan_runner.h
src/utils/util_io.h

…running plan
- ❌ This PR needs [link]
- ❌ [link] needs this PR
4. ✅ New code follows …

add user stop check to main loop, clear buffered plan if robot in wrong mode

---

src/driver/communication_interface.cc
src/driver/communication_interface.h
src/driver/franka_plan_runner.cc
src/driver/franka_plan_runner.h

Refactor into separate ImpedanceControlCallback

---

CMakeLists.txt
src/driver/franka_plan_runner.cc
src/driver/franka_plan_runner.h

cleanup that didn't get pushed with the sim code

cmake cleanup 

---

src/driver/communication_interface.cc
src/driver/communication_interface.h
src/driver/franka_plan_runner.cc

fix memory leak

---

src/driver/franka_plan_runner.cc

- Publish driver status after successful error recovery
6. ❌ I have included Doxygen-style documentation in the new C++ code.
Please verify that all sections are accurately filled out and …

Publish driver status after successful error recovery

---

src/driver/franka_plan_runner.cc

- Only initialize unique ptr once when connecting to robot
- 
Please verify that all sections are accurately filled out …

Only initialize unique ptr once

---

.circleci/config.yml
CMakeLists.txt

use standard catkin setup for catkin modules

---

src/driver/communication_interface.cc
src/driver/communication_interface.h
src/driver/franka_plan_runner.cc
src/driver/franka_plan_runner.h
src/utils/robot_parameters.cc
src/utils/robot_parameters.h
src/utils/util_conv.cc
src/utils/util_conv.h

Publish franka state over lcm
- ✅ Publish franka state over lcm
- ✅ This PR needs https://github.com/DexaiRobotics/robot_msgs/pull/21
- ✅ Current plan utime
- ✅ Plan completion fraction
Please verify that all sections are accurately filled out and that all 6 numbered entries above …

Publish franka state over lcm (superset of iiwa status)

---

src/driver/communication_interface.cc

- Print integer value of invalid mode for debugging purposes
1. ✅Tested on simulated robot: [Describe the tests/commands used.]
5. ✅New code passed `clang-format` and `cpplint` at least, if not all of our static code analysers.
6. ❌ I have included Doxygen-style documentation in the new C++ code.
Please verify that all sections are accurately filled out and …

Print value of invalid mode

---

franka.sh

- ✅❌ This PR needs [https://github.com/DexaiRobotics/deploy/pull/177
4. ✅ New code follows established C++17 best practices ([C++ Core …

Check if a driver instance is already running

---

.circleci/config.yml
CMakeLists.txt
franka.sh

- ✅ spdlog 1.9.2 support
- ❌ This PR needs [link]
- ❌ [link] needs this PR
Please verify that all sections are …

feat: spdlog 1.9.2 support

---

.circleci/config.yml
src/driver/communication_interface.cc
src/driver/communication_interface.h

Resend confirmation of duplicate incoming plan

---

src/driver/franka_plan_runner.cc

Publish plan completion after simulated control exception

---

src/driver/franka_plan_runner.cc

- Check for mode before setting collision behavior in automatic error recovery
- Fixes DFD crash when trying to set collision behavior when robot is locked
4. ✅ New …

Check for mode before setting collision behavior in automatic error recovery

---

src/driver/communication_interface.cc

- https://dexai.slack.com/archives/CJFAY3KT5/p1642690230175000
Please verify that all sections are accurately filled out …

Set plan completion after rejecting plans

---

src/driver/communication_interface.cc
src/driver/communication_interface.h

Publish user stopped when in guiding mode

---

src/driver/franka_plan_runner.cc

- https://dexairobotics.atlassian.net/browse/DEX-5529
Please verify that all sections are accurately filled out …

Reset plan before attempting automatic error recovery which can be blocking

---

src/driver/franka_plan_runner.cc

Had a Franka driver crash a while back https://dexai.slack.com/archives/CTUFJ4WVA/p1662666227392549?thread_ts=1661806569.565029&cid=CTUFJ4WVA
```
56  [2022-08-29 16:54:55.745] [franka_driver] [info] RunFranka: robot is running and waiting for a new plan...
57	control_command_success_rate: 0.97 
58	control_command_success_rate: 1. 
59	terminate called after throwing an instance of 'franka::CommandException'
60	what():  libfranka: Automatic Error Recovery command rejected: command not possible in the current mode! 
/src/drake-franka-driver/franka.sh: line 62:    14 Aborted                 (core dumped) ./build/franka_driver $config $@
```
we already have logic around the automatic error recovery which is supposed to check modes, but apparently this didn't work (maybe mode changed after the …

Try-catch around error recovery and print statement if it fails

---

src/driver/communication_interface.cc

sim brakes event
- ✅  sim brakes event
1. ✅ Tested on simulated robot: Tested in sim
Please verify that all sections are accurately filled out and that all 6 numbered entries above are present and ticked/checked off, with their requirements met, if applicable.

sim brakes event
