DexaiRobotics/drake-franka-driver

- include/communication_interface.h
- src/communication_interface.cc
- Broadcast user stop status as a bool
- ❌  Combine user stop status, estop status, robot status into single message definition
1. ✅ Tested on simulated robot: Ran franka driver, verified topic being published
6. ✅❌ I have included Doxygen-style …
> Sw.user stop.broadcast

- setup.sh
Add communication_test to be build when setup.sh is called.  Building all targets was much slower.
Add communication_test to be build when setup.sh is called.
1. ✅ Tested on simulated robot: Ran build, verified communication_test was built
6. ❌ I have included Doxygen-style documentation in the new C++ code. (not needed)
Please verify that all sections are accurately filled out and that all 6 numbered entries above …
> Add communication_test to be build by default

- include/communication_interface.h
- src/communication_interface.cc
- src/franka_plan_runner.cc
Publish DRIVER_STATUS if franka brakes are locked
- ✅ Publish DRIVER_STATUS false if franka brakes are locked and driver is unable to accept plans
- ✅ Publish a bool <robot>_BRAKES_LOCKED status
Please verify that all sections are accurately filled out and that all 6 numbered …
> Publish DRIVER_STATUS false if unable to receive commands

- src/franka_plan_runner.cc
- src/util_conv.cc
- This prevents us from bailing early and creating unnecessary duplicate logs each time driver fails to start. Just keep trying...
1. ✅Tested on simulated robot: [Describe the tests/commands used.]
2. ✅ Tested on physical robot: Tried starting up while user stopped or not connected to franka, verified it keeps retrying until connection can be established
5. ✅ New code passed `clang-format` and `cpplint` at least, if not …
> Retry when attempting to connect to Franka for first time

- include/communication_interface.h
- src/communication_interface.cc
- src/franka_plan_runner.cc
Check if the cobot is user stopped on startup
- ✅ Check if user stopped on startup, if so send a message
1. ✅ Tested on simulated robot: Tested with TLE 
2. ✅ Tested on physical robot: Tested on `krieger` 
Please verify that all sections are accurately filled out and that all 6 numbered entries above are present and ticked/checked off, with their requirements met, if applicable.
> Check if user stopped on startup

- include/communication_interface.h
- include/franka_plan_runner.h
- src/communication_interface.cc
- src/franka_plan_runner.cc
- Add ability to simulate control exceptions
- ✅ https://github.com/DexaiRobotics/deploy/pull/134 needs this PR
1. ✅ Tested on simulated robot: `cmd driver_event control_exception` triggers a control exception
6. ✅ I have included Doxygen-style documentation …
> Sw.sim.control exception

- src/driver/communication_interface.cc
- src/driver/franka_plan_runner.cc
- Fix sim franka initializing to user stopped: offending code was 
```c++
void CommunicationInterface::ResetData() {
std::unique_lock<std::mutex> lock_data(robot_data_mutex_);
robot_data_.has_robot_data = false;
robot_data_.robot_state = franka::RobotState();
lock_data.unlock();
```
the `RobotState` constructor default to user stopped mode
1. ✅Tested on simulated robot: [Describe the tests/commands used.]
4. ✅ New code follows established C++17 best practices ([C++ Core …
> Sw.user stop.debug

- src/driver/communication_interface.cc
- src/driver/communication_interface.h
- src/driver/franka_plan_runner.cc
- src/driver/franka_plan_runner.h
- src/utils/robot_parameters.cc
- src/utils/robot_parameters.h
Add a compliant push that uses a cartesian impedance controller to push along the z-axis in the end effector frame
- ✅ see above
- ❌ https://github.com/DexaiRobotics/dig/pull/703
- ❌ Needs sim handler for compliant push start and stop
- ❌ Needs  flag based on envvar/params to disable compliant push and "fake it" until we can verify that torque control works on all robots
5. ✅ New code passed `clang-format` and `cpplint` at least, if not all of our …
> Bgc.compliant.push

- src/driver/franka_plan_runner.cc
- Fixes unrecoverable server error occurring if robot user stopped on startup and driver killed
- Publish u-stop status in loop before connection to robot established
2. ✅ Tested on physical robot: tried restarting driver on u-stopped robot, verified successful connection
3. ✅New code is written in pure C++17 to the best of my knowledge.
5. ✅ New code passed `clang-format` and `cpplint` at least, if not all of our static …
> Model.init.fix

- src/driver/communication_interface.h
- src/driver/franka_plan_runner.cc
- Published both locked and user stopped status during startup loop
2. ✅ Tested on physical robot: tested publishing of both channels if robot is stuck in startup loop
6. ❌ I have included Doxygen-style documentation in the new C++ code.
Please verify that …
> Published both locked  and user stopped status during startup loop

- src/driver/communication_interface.cc
- src/driver/communication_interface.h
- src/driver/franka_plan_runner.cc
- src/driver/franka_plan_runner.h
- src/utils/util_conv.cc
- src/utils/util_conv.h
- Process `cartesian_goal` and `exec_opt` in `robot_spline_t`
- Execute plan until contact as specified by `cartesian_goal`
- ✅ Process `cartesian_goal` and `exec_opt` in `robot_spline_t`
- ✅ Execute plan until contact as specified by `cartesian_goal`
- ✅❌ https://github.com/DexaiRobotics/dig/pull/813 needs this PR
2. ✅ Tested on physical robot: [Ran tool change with tool centering on vine on `jello`]
6. ✅ I have …
> Execute plan until contact

- src/driver/communication_interface.cc
- src/driver/communication_interface.h
- src/utils/util_conv.cc
- Some auto-retry and better reporting when we get garbage mode values from Franka controller
5. ✅❌ New code passed `clang-format` and `cpplint` at …
> Sw.mode.unknown

- src/driver/franka_plan_runner.cc
- src/driver/franka_plan_runner.h
Fix segfault on user-triggered control exception in sim driver 
- ✅ Fix segfault on user-triggered control exception in sim driver 
Please verify that all sections are accurately filled out and that all 6 numbered entries above are present and ticked/checked off, with their …
> Fix segfault on user-triggered control exception in sim driver

- franka.sh
- Remove print statement saying franka failed to start if driver is killed
5. ✅❌ New code passed `clang-format` and `cpplint` at least, if not all of …
> Remove print statement saying franka failed to start if driver is killed

- .circleci/config.yml
- src/driver/constraint_solver.cc
Resolved deprecation warning from Drake by switching to the newer collision filter management workflow.
- ✅ Doesn't have Drake Deprecation warning
- ❌ New feature is accompanied by new test: Same behavior, different workflow.
- ✅❌ This PR in paired with [dig/#1087](https://github.com/DexaiRobotics/dig/pull/1087)
6. ✅ I have included Doxygen-style …
> Use new collision filter management from Drake

- src/driver/communication_interface.cc
- src/driver/communication_interface.h
- src/driver/franka_plan_runner.cc
- Fix high LCM publish rate when robot is user stopped by removing duplicate publishing
- ❌ Consolidate into publishing all aspects of robot status (brakes locked, user stop, driver status) into single LCM channel
1. ✅ Tested on simulated robot: Tested `back_and_forth`
2. ✅ Tested on physical robot: Tested publish rate when user stopped during operation and on startup, and `back_and_forth`
5. ✅ New code passed …
> Fix publishing rate for brakes locked, ustop, and driver status

- src/driver/communication_interface.cc
- src/driver/communication_interface.h
- src/driver/franka_plan_runner.cc
- src/driver/franka_plan_runner.h
- src/utils/robot_parameters.cc
- src/utils/robot_parameters.h
Consolidate multiple LCM channels into single driver status channel with information about current plan number, user stop, brakes, pause, torque status and other driver metadata.
1. ✅  Tested on simulated robot: tested `back_and_forth` with control exceptions
5. ✅❌ New code passed `clang-format` and `cpplint` at least, if not all of our static code …
> Publish to consolidated driver status message

- src/driver/franka_plan_runner.cc
Fixes crash when `CommandException` is thrown: 
```
franka-driver-deploy | [2021-12-14 17:26:23.768] [franka_driver] [warning] RunFranka: robot is in Reflex mode at startup, trying automaticErrorRecovery...
franka-driver-deploy | terminate called after throwing an instance of 'franka::CommandException'
franka-driver-deploy |   what():  libfranka: Automatic Error Recovery command rejected: manual error recovery required!
franka-driver-deploy | /src/drake-franka-driver/franka.sh: line 62:    14 Aborted                 (core dumped) ./build/franka_driver $config $@
franka-driver-deploy | ~
```
1. ❌ Tested on simulated robot: …
> Catch all Franka exceptions, not just ControlException, during init

- src/driver/franka_plan_runner.cc
- Fix driver crash on real robot when a simulated control exception is triggered
2. ✅ Tested on physical robot: ran `back_and_forth` with `cmd franka driver_event control_exception`
3. ✅New code is written in pure C++17 to the best of my knowledge.
5. ❌ New code passed `clang-format` and `cpplint` at least, if not all of our static code analysers.
Please …
> Fix driver crash on real robot when a simulated control exception is triggered

- src/driver/communication_interface.cc
- src/driver/communication_interface.h
- src/driver/franka_plan_runner.cc
- src/driver/franka_plan_runner.h
- Add timing on plan preprocessing before execution
Please verify that all sections are accurately filled out and …
> Add timing on plan preprocessing before execution

- src/driver/communication_interface.cc
- src/driver/franka_plan_runner.cc
- Publish driver status even if robot is locked
- https://github.com/DexaiRobotics/dig/pull/1875 needs this PR
5. ✅❌ New code passed `clang-format` and `cpplint` at least, if not all of our static code …
> Publish driver status even if robot is locked

- src/driver/franka_plan_runner.cc
- Follow-on to https://github.com/DexaiRobotics/drake-franka-driver/pull/132 as setting collision behavior also issues a command exception
- https://dexai.slack.com/archives/CTUFJ4WVA/p1664899362058659?thread_ts=1664899343.578519&cid=CTUFJ4WVA
- https://github.com/DexaiRobotics/drake-franka-driver/pull/132
4. ✅ New code follows established C++17 best practices ([C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCor …
> Expand try catch in automatic error recovery

- src/driver/constraint_solver.cc
`Publish` Method is deprecated in Drake 1.10. Replacing it with `ForcedPublish`
https://github.com/DexaiRobotics/fullstack/pull/2952 
Please verify that all sections are accurately filled out and that all 6 numbered entries above are present and ticked/checked off, with their …
> One line change: ForcedPublish for compatibility with Drake 1.10

- .pre-commit-config.yaml
- setup.sh
gcc7 is deprecated in the ubuntu apt universe. gcc9 is the last compatible compiler for libfranka 0.8 and it won't build on anything newer. we should upgrade soon
- This PR needs [link]
- [link] needs this PR …
> chore: build libfranka with gcc9; update hooks

- src/driver/franka_plan_runner.cc
- src/driver/franka_plan_runner.h
reduce log verbosity by increasing how long we wait between retries, when we fail to init in reflex mode. fixes: https://dexairobotics.atlassian.net/browse/DEX-7215
- ✅ reduce log verbosity when we fail to init in reflex mode. 
Please verify that all sections are accurately filled …
> reduce log verbosity when we fail to init in reflex mode

- src/driver/communication_interface.cc
- src/driver/communication_interface.h
- src/driver/franka_plan_runner.cc
- src/driver/franka_plan_runner.h
In situations where communication between the Franka controller and driver is interrupted, and a user stop is subsequently issued to the Franka, it is possible for the release of the user stop to result in the system erroneously resuming motion without user input. Deeper dive [here](https://dexai.slack.com/archives/C03R65J58LV/p1706215664331639?thread_ts=1706109164.478469&cid=C03R65J58LV).
- ✅ Clear new plans from the comms interface when in `User Stopped` or `Locked` Franka modes as part of automatic recovery, before continuing onward.
1. ✅❌ Tested on simulated robot: …
> Clear next plan when recovering from user stop

- src/driver/franka_driver.cc
/var/run is not writeable by normal user (or anyone other than root) so use home dir.
- ✅ Fix driver permissions
1. ✅ Tested on simulated robot: Verified it started up, and running a second one would kill the first.
Please verify that all sections are accurately filled out and that all 6 numbered entries above are present and ticked/checked off, …
> Move pid file to somewhere that doesn't need root to write to it
